name: Build and Test on macOS

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:
    branches: [ main, dev ]
    
jobs:
  macOS:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@main
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
